from __future__ import annotations

import json
from pathlib import Path

from .models import VerificationReport


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(report: VerificationReport) -> str:
    lines = [
        "# AdapterGuard verification report",
        "",
        f"**Verdict:** {report.verdict}",
        "",
    ]

    if report.fingerprints:
        lines.extend(
            [
                "## Artifact fingerprints",
                "",
                "| Artifact | Mode | SHA-256 | Source |",
                "| --- | --- | --- | --- |",
            ]
        )
        for label, fingerprint in report.fingerprints.items():
            lines.append(
                f"| {_escape(label)} | {_escape(fingerprint.mode)} | "
                f"`{fingerprint.sha256}` | `{_escape(fingerprint.source)}` |"
            )
        lines.append("")

    lines.extend(
        [
            "## Checks",
            "",
            "| Status | Check | Result |",
            "| --- | --- | --- |",
        ]
    )
    for check in report.checks:
        lines.append(
            f"| {check.status.value.upper()} | {_escape(check.name)} | {_escape(check.message)} |"
        )
    lines.append("")

    evidence_checks = [check for check in report.checks if check.evidence]
    if evidence_checks:
        lines.extend(["## Prompt-level evidence", ""])
        for check in evidence_checks:
            lines.extend(
                [
                    f"### {_escape(check.name)}",
                    "",
                    "| # | Prompt SHA-256 | Mean diff | Max diff | Top-1 agreement | "
                    "First divergent position | Prediction A → B |",
                    "| ---: | --- | ---: | ---: | ---: | ---: | --- |",
                ]
            )
            for item in check.evidence or []:
                position = (
                    str(item.first_divergent_position)
                    if item.first_divergent_position is not None
                    else "—"
                )
                prediction = "—"
                if item.left_token_id is not None and item.right_token_id is not None:
                    left = (
                        item.left_token if item.left_token is not None else str(item.left_token_id)
                    )
                    right = (
                        item.right_token
                        if item.right_token is not None
                        else str(item.right_token_id)
                    )
                    prediction = f"`{_escape(left)}` → `{_escape(right)}`"
                lines.append(
                    f"| {item.prompt_index} | `{item.prompt_sha256}` | "
                    f"{item.mean_abs_logit_diff:.6g} | {item.max_abs_logit_diff:.6g} | "
                    f"{item.top1_token_agreement:.6g} | {position} | {prediction} |"
                )
                if item.prompt is not None:
                    lines.append("")
                    lines.append(f"> Prompt #{item.prompt_index}: `{_escape(item.prompt)}`")
                    lines.append("")
            lines.append("")

    lines.extend(
        [
            "---",
            "Generated by [AdapterGuard](https://github.com/ptrgiang/adapterguard).",
            "",
        ]
    )
    return "\n".join(lines)


def write_json_report(report: VerificationReport, path: str | Path) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report.to_dict(), indent=2) + "\n", encoding="utf-8")
    return output


def write_markdown_report(report: VerificationReport, path: str | Path) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(report), encoding="utf-8")
    return output
